# docker compose versions
version: '2'

# shared volumes
volumes:
  project:
  yarn_cache:

services:
  # web app bundle build
  app:
    image: openneuro/app:${CRN_APP_TAG}
    command: sh -c "yarn install --pure-lockfile && yarn start"
    volumes:
      - ../openneuro:/srv
      - yarn_cache:/root/.cache
      - project:/srv/app/dist
    tmpfs:
      - /srv/app/node_modules:exec

  # crn core (bids-core)
  core:
    volumes:
      - ../bids-core:/srv/bids-core
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data

  # crn node server
  server:
    command: sh -c "yarn install && node /srv/crn-server/index.js"
    volumes:
      - ../openneuro/server:/srv/crn-server
      - yarn_cache:/root/.cache
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/crn-server/persistent
    tmpfs:
      - /srv/crn-server/node_modules:exec

  worker:
    command: sh -c "yarn install  && node /srv/crn-server/worker.js"
    volumes:
      - ../openneuro/server:/srv/crn-server
      - yarn_cache:/root/.cache
      - ./server/client.config.js:/srv/crn-server/client.config.js:rw
      - ${PERSISTENT_DIR}/bids-core/persistent/data:/srv/bids-core/persistent/data
      - ${PERSISTENT_DIR}/crn-server/persistent:/srv/crn-server/persistent
    tmpfs:
      - /srv/crn-server/node_modules:exec

  # nginx - static file serving and service proxy
  nginx:
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "9876:80"
      - "8110:8110"
      - "8443:443"
