apiVersion: v1
name: openneuro
version: 1.0.5
description: OpenNeuro production deployment chart
home: https://openneuro.org
sources:
  - https://github.com/openNeuroOrg/openneuro
appVersion: 3.8.2
dependencies:
  - name: redis
    version: 7.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: efs-provisioner
    version: 0.3.7
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: aws-alb-ingress-controller
    version: 0.1.8
    repository: https://kubernetes-charts-incubator.storage.googleapis.com/
