apiVersion: v1
name: openneuro
version: 1.0.0
description: OpenNeuro production deployment chart
home: https://openneuro.org
sources:
  - https://github.com/openNeuroOrg/openneuro
appVersion: 3.1.5-1
dependencies:
  - name: redis
    version: 7.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
  - name: efs-provisioner
    version: 0.3.7
    repository: https://kubernetes-charts.storage.googleapis.com/
