apiVersion: v1
name: openneuro
version: 1.8.0
description: OpenNeuro production deployment chart
home: https://openneuro.org
sources:
  - https://github.com/openNeuroOrg/openneuro
appVersion: 4.45.3
dependencies:
  - name: redis
    version: 22.0.7
    repository: https://charts.bitnami.com/bitnami
