apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-beat-scheduler
  labels:
    app: '{{ .Release.Name }}-beat-scheduler'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-beat-scheduler
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-beat-scheduler
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: {{ .Release.Name }}-beat-scheduler
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        resources:
          limits:
            cpu: "0.5"
            memory: "2Gi"
          requests:
            cpu: "0.1"
            memory: "1Gi"
        command:
          - /beat-scheduler
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret

