apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-datalad-service
  labels:
    app: {{ .Release.Name }}-datalad-service
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-datalad-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-datalad-service
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-datasets
      containers:
      - name: {{ .Release.Name }}-datalad-service
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "0.5"
        ports:
        - containerPort: 9877
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
        volumeMounts:
        - name: datasets
          mountPath: /datalad

