apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-publish-worker
  labels:
    app: '{{ .Release.Name }}-publish-worker'
    chart: '{{ .Chart.Name }}-{{ .Chart.Version }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-publish-worker
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-publish-worker
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
    spec:
      volumes:
      - name: datasets
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-datasets
      - name: ssh-key
        secret:
          secretName: {{ .Release.Name }}-ssh-key
          items:
          - key: datalad-key
            path: datalad-key
            mode: 0400
      containers:
      - name: {{ .Release.Name }}-publish-worker
        image: 'openneuro/datalad-service:v{{ .Chart.AppVersion }}'
        resources:
          limits:
            cpu: "0.5"
            memory: "2Gi"
          requests:
            cpu: "0.1"
            memory: "1Gi"
        command:
          - /publish-worker
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-configmap
        - secretRef:
            name: {{ .Release.Name }}-secret
        volumeMounts:
        - name: datasets
          mountPath: /datalad
        - name: ssh-key
          mountPath: /datalad-key
          subPath: datalad-key
